# docker-compose.yml
version: "2"

networks:
  my_network:
    driver: bridge

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.6-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - my_network
  redis:
    container_name: redis
    image: redis:3.2-alpine
    ports:
      - 6379:6379
    networks:
      - my_network
